# Generated by Django 5.2.6 on 2025-10-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("arches_search", "0003_add_advanced_search_facets"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="booleansearch",
            new_name="arches_sear_graph_s_cdea05_idx",
            old_name="arches_sear_graph_a_bd97e5_idx",
        ),
        migrations.RenameIndex(
            model_name="daterangesearch",
            new_name="arches_sear_graph_s_bfe863_idx",
            old_name="arches_sear_graph_a_a0d51a_idx",
        ),
        migrations.RenameIndex(
            model_name="datesearch",
            new_name="arches_sear_graph_s_253090_idx",
            old_name="arches_sear_graph_a_b60884_idx",
        ),
        migrations.RenameIndex(
            model_name="numericsearch",
            new_name="arches_sear_graph_s_6907be_idx",
            old_name="arches_sear_graph_a_a6ce74_idx",
        ),
        migrations.RenameIndex(
            model_name="termsearch",
            new_name="arches_sear_graph_s_a10c9b_idx",
            old_name="arches_sear_graph_a_0c8ffe_idx",
        ),
        migrations.RenameIndex(
            model_name="uuidsearch",
            new_name="arches_sear_graph_s_ed63db_idx",
            old_name="arches_sear_graph_a_c2a8c5_idx",
        ),
    ]
