# Generated by Django 5.2.6 on 2025-10-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arches_search", "0005_ddatatypexadvancedsearch"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booleansearch",
            index=models.Index(
                fields=["graph_slug", "node_alias", "resourceinstanceid"],
                name="arches_sear_graph_s_f9da56_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booleansearch",
            index=models.Index(
                fields=["graph_slug", "node_alias", "value"],
                name="arches_sear_graph_s_7d4115_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="daterangesearch",
            index=models.Index(
                fields=["graph_slug", "node_alias", "resourceinstanceid"],
                name="arches_sear_graph_s_ffe7f6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="daterangesearch",
            index=models.Index(
                fields=["graph_slug", "node_alias", "start_value", "end_value"],
                name="arches_sear_graph_s_39b677_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datesearch",
            index=models.Index(
                fields=["graph_slug", "node_alias", "resourceinstanceid"],
                name="arches_sear_graph_s_7d5e61_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datesearch",
            index=models.Index(
                fields=["graph_slug", "node_alias", "value"],
                name="arches_sear_graph_s_455ff1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="numericsearch",
            index=models.Index(
                fields=["graph_slug", "node_alias", "resourceinstanceid"],
                name="arches_sear_graph_s_108656_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="numericsearch",
            index=models.Index(
                fields=["graph_slug", "node_alias", "value"],
                name="arches_sear_graph_s_4a34b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="termsearch",
            index=models.Index(
                fields=["graph_slug", "node_alias", "resourceinstanceid"],
                name="arches_sear_graph_s_29d42b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="termsearch",
            index=models.Index(
                fields=["graph_slug", "node_alias", "value"],
                name="arches_sear_graph_s_6f7745_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="uuidsearch",
            index=models.Index(
                fields=["graph_slug", "node_alias", "resourceinstanceid"],
                name="arches_sear_graph_s_bf96ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="uuidsearch",
            index=models.Index(
                fields=["graph_slug", "node_alias", "value"],
                name="arches_sear_graph_s_c0fa2b_idx",
            ),
        ),
    ]
