# Generated by Django 5.2.6 on 2025-11-21 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arches_search", "0006_add_more_specific_indices_to_search_tables"),
        ("models", "12394_resource_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booleansearch",
            name="resourceinstanceid",
            field=models.ForeignKey(
                db_column="resourceinstanceid",
                on_delete=django.db.models.deletion.CASCADE,
                to="models.resourceinstance",
            ),
        ),
        migrations.AlterField(
            model_name="booleansearch",
            name="tileid",
            field=models.ForeignKey(
                db_column="tileid",
                on_delete=django.db.models.deletion.CASCADE,
                to="models.tile",
            ),
        ),
        migrations.AlterField(
            model_name="daterangesearch",
            name="resourceinstanceid",
            field=models.ForeignKey(
                db_column="resourceinstanceid",
                on_delete=django.db.models.deletion.CASCADE,
                to="models.resourceinstance",
            ),
        ),
        migrations.AlterField(
            model_name="daterangesearch",
            name="tileid",
            field=models.ForeignKey(
                db_column="tileid",
                on_delete=django.db.models.deletion.CASCADE,
                to="models.tile",
            ),
        ),
        migrations.AlterField(
            model_name="datesearch",
            name="resourceinstanceid",
            field=models.ForeignKey(
                db_column="resourceinstanceid",
                on_delete=django.db.models.deletion.CASCADE,
                to="models.resourceinstance",
            ),
        ),
        migrations.AlterField(
            model_name="datesearch",
            name="tileid",
            field=models.ForeignKey(
                db_column="tileid",
                on_delete=django.db.models.deletion.CASCADE,
                to="models.tile",
            ),
        ),
        migrations.AlterField(
            model_name="numericsearch",
            name="resourceinstanceid",
            field=models.ForeignKey(
                db_column="resourceinstanceid",
                on_delete=django.db.models.deletion.CASCADE,
                to="models.resourceinstance",
            ),
        ),
        migrations.AlterField(
            model_name="numericsearch",
            name="tileid",
            field=models.ForeignKey(
                db_column="tileid",
                on_delete=django.db.models.deletion.CASCADE,
                to="models.tile",
            ),
        ),
        migrations.AlterField(
            model_name="termsearch",
            name="resourceinstanceid",
            field=models.ForeignKey(
                db_column="resourceinstanceid",
                on_delete=django.db.models.deletion.CASCADE,
                to="models.resourceinstance",
            ),
        ),
        migrations.AlterField(
            model_name="termsearch",
            name="tileid",
            field=models.ForeignKey(
                db_column="tileid",
                on_delete=django.db.models.deletion.CASCADE,
                to="models.tile",
            ),
        ),
        migrations.AlterField(
            model_name="uuidsearch",
            name="resourceinstanceid",
            field=models.ForeignKey(
                db_column="resourceinstanceid",
                on_delete=django.db.models.deletion.CASCADE,
                to="models.resourceinstance",
            ),
        ),
        migrations.AlterField(
            model_name="uuidsearch",
            name="tileid",
            field=models.ForeignKey(
                db_column="tileid",
                on_delete=django.db.models.deletion.CASCADE,
                to="models.tile",
            ),
        ),
    ]
