# Generated by Django 5.2.12 on 2026-03-09 23:23

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ("arches_search", "0008_termsearch_search_vector_and_more"),
        ("models", "12547_fix_db_nodevalue_display_value"),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.RemoveIndex(
            model_name="termsearch",
            name="arches_sear_value_8a4617_idx",
        ),
        migrations.RemoveIndex(
            model_name="termsearch",
            name="arches_sear_graph_s_6f7745_idx",
        ),
        migrations.RemoveIndex(
            model_name="termsearch",
            name="arches_sear_graph_s_2ae457_idx",
        ),
        migrations.RemoveIndex(
            model_name="termsearch",
            name="arches_sear_graph_s_a81e44_idx",
        ),
        migrations.RemoveIndex(
            model_name="termsearch",
            name="arches_sear_graph_s_1350d9_idx",
        ),
        migrations.AddIndex(
            model_name="termsearch",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["graph_slug", "node_alias", "value"],
                name="gslug_na_val",
                opclasses=["text_ops", "text_ops", "gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="termsearch",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["graph_slug", "node_alias", "language", "value"],
                name="gslug_na_lang_val",
                opclasses=["text_ops", "text_ops", "text_ops", "gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="termsearch",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["graph_slug", "node_alias", "tileid", "value"],
                name="gslug_na_tile_val",
                opclasses=["text_ops", "text_ops", "uuid_ops", "gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="termsearch",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["graph_slug", "node_alias", "tileid", "language", "value"],
                name="gslug_na_tile_lang_val",
                opclasses=[
                    "text_ops",
                    "text_ops",
                    "uuid_ops",
                    "text_ops",
                    "gin_trgm_ops",
                ],
            ),
        ),
    ]
