# Generated by Django 6.1 on 2026-09-03 15:12

import arches.app.models.fields.i18n
import arches.app.utils.betterJSONSerializer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arches_search", "0021_daterangesearch_end_value_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceFieldFacet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "field_class",
                    models.CharField(
                        help_text="Dotted path of the Django model field class this facet applies to, e.g. 'django.db.models.BooleanField'. Matched by isinstance, so a more specific class takes precedence over its base.",
                        max_length=255,
                        verbose_name="Field Class",
                    ),
                ),
                (
                    "label",
                    arches.app.models.fields.i18n.I18n_TextField(
                        default="",
                        encoder=arches.app.utils.betterJSONSerializer.JSONSerializer,
                    ),
                ),
                ("operator", models.CharField(max_length=50)),
                ("arity", models.PositiveSmallIntegerField(default=0)),
                ("param_formats", models.JSONField(blank=True, default=list)),
                ("orm_template", models.CharField(blank=True, max_length=255)),
                ("is_orm_template_negated", models.BooleanField(default=False)),
                ("sortorder", models.PositiveSmallIntegerField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("field_class", "operator"),
                        name="unique_operator_per_field_class",
                    )
                ],
            },
        ),
    ]
