# Generated by Django 6.1 on 2026-09-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arches_search", "0023_seed_resource_field_facets"),
    ]

    operations = [
        migrations.AddField(
            model_name="termsearch",
            name="valuetype",
            field=models.TextField(default=""),
        ),
    ]
