[build-system]
requires = [ "setuptools>=77", "setuptools-scm",]
build-backend = "setuptools.build_meta"

[project]
name = "arches-search"
version = "0.1.0a18"
readme = "README.md"
requires-python = ">=3.12"
license = "AGPL-3.0-or-later"
authors = []
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: Django",
    "Framework :: Django :: 6.1",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "arches @ git+https://github.com/archesproject/arches.git@cbyrd/12934-migrate-to-openvue",
    "arches-controlled-lists @ git+https://github.com/archesproject/arches-controlled-lists.git@cbyrd/migrate-to-openvue",
    "arches-modular-reports @ git+https://github.com/archesproject/arches-modular-reports.git@cbyrd/migrate-to-openvue",
    "arches-resource-sets>=0.1.0a0",
    "arches-vue-components @ git+https://github.com/archesproject/arches-vue-components.git@cbyrd/migrate-to-openvue",
]
dynamic = []

[tool.setuptools]
packages = [ "arches_search",]

[dependency-groups]
dev = [ "black==26.3.1", "coverage", "django-silk==5.5.0", "livereload", "pre-commit==4.6.1", "sst",]
